### ISSUE TITLE
Buffer specs for Sound.create()

### ISSUE THREAD

**Issue by NHQ** [xk/node-sound#3]
I'm trying to couple node-sound with [audiolib.js](https://github.com/jussi-kalliokoski/audiolib.js/)

But when I try to pass a buffer from audiolib to node-sound, the get no audio.

Must the buffer be 16 bit signed Int?

**Comment by xk** [comment]
Hi NHQ,

Yes, the buffer must be a PCM sound, 16 bits per sample (signed), stereo @ 44100 Hz (samples per second). If you look at the files test-multiwaves, test-sinewave, squarewave etc. you'll see how to synthesize a sound. I don't know much about audiolib, but if it can export a sound in PCM 16 bits stereo @ 44100 Hz it should work fine with node-sound. If it doesn't, you could try to save audiolib's sound to a file and let node-sound bufferify() it. Hope it helps.
