### ISSUE TITLE
Switching audio output while in use mutes node-sound player

### ISSUE THREAD

**Issue by wiill** [xk/node-sound#4]
When accidentally unplugging my audio jack from earphones plug of my macbook (MBP 13", Mac OSX 10.6 SnowLeopard), whether while playing a sound or not, mutes node-sound and there is no way to get it back on, even when replugging the jack.

This happens the other way as well: when starting to play on computer default audio output and then plugging a jack definitely mutes node-sound.

The only way to get node-sound back on is to terminate my nodejs app and relaunch it.

No specific logs in my nodejs app console about this when happening.

**Comment by xk** [comment]
Thank you, looking into it...

**Comment by wiill** [comment]
An additional piece of information: issue happens when computer goes asleep with node program running.
Once up again, sounds module is muted.

Still no logs in console

**Comment by xk** [comment]
Thanks, I've got no solution for this problem yet...

**Comment by wiill** [comment]
It's been a longtime, but still using it ;)
Just dropped by to say it doesn't occur anymore since later Mac OS versions (after Snow Leopard)

Cheers, and thanks
